name: dmake
version: 0.0.0
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  args: ^1.0.0
  glob: ^1.0.0
  graphs: ^0.1.2
  io: ^0.3.2
  logging: ^0.11.0
  mime: ^0.9.6
  path: ^1.0.0
executables:
  dmake: dmake